### ISSUE TITLE
App runner + Aurora serverless

### ISSUE THREAD

**Issue by jad-haddad** [DougTrajano/mlflow-server#124]
Hello,
AWS announced a few days ago the VPC support in App Runner (https://github.com/aws/apprunner-roadmap/issues/1#issuecomment-1033181127) , I wasn't able to do the necessary Terraform changes...
However, I configured it using the AWS console and I'm facing an issue with the DB, the MLflow app always keeps active connections to the Aurora serverless DB, and so there is always a capacity unit always active, which kind of defeats the purpose of serverless. Any idea how to fix this?

I had to pause the MLflow app runner instance so that the capacity units went down to 0
![image](https://user-images.githubusercontent.com/27054843/153384147-76abb7f4-09d1-4b60-8844-689bf12af660.png)

Thank you

**Comment by DougTrajano** [comment]
Hey buddy! Nice to hear that we have it on AWS App Runner now.

I don't know exactly the reason that MLflow maintains the connection active all the time, we need to take a look at the MLflow source code to understand why.

I'm busy this and the next few weeks, but I'll try to update this project at the end of the month.
