### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by SyedHamza0196** [DougTrajano/mlflow-server#129]
All the creation went successfully and service_url was logged. When i access the url with https:// prefix and with/without :8080 postfix the returns 502 Bad Gateway error

Logs are:

random_password.backend_store: Creating...
random_password.mlflow_password: Creating...
random_password.backend_store: Creation complete after 0s [id=none]
random_password.mlflow_password: Creation complete after 0s [id=none]
aws_iam_role.iam_role: Creating...
aws_db_instance.backend_store: Creating...
aws_s3_bucket.artifact_store[0]: Creating...
aws_iam_role.iam_role: Creation complete after 5s [id=mlflow-dev-role]
aws_db_instance.backend_store: Still creating... [10s elapsed]
aws_s3_bucket.artifact_store[0]: Still creating... [10s elapsed]
aws_s3_bucket.artifact_store[0]: Still creating... [20s elapsed]
aws_db_instance.backend_store: Still creating... [20s elapsed]
aws_s3_bucket.artifact_store[0]: Creation complete after 22s [id=mlflow-dev-20220220130916663600000001]
aws_iam_role_policy.bucket_policy[0]: Creating...
aws_iam_role_policy.bucket_policy[0]: Creation complete after 3s [id=mlflow-dev-role:access_to_mlflow_bucket20220220130939392200000002]
aws_db_instance.backend_store: Still creating... [30s elapsed]
aws_db_instance.backend_store: Still creating... [40s elapsed]
aws_db_instance.backend_store: Still creating... [50s elapsed]
aws_db_instance.backend_store: Still creating... [1m0s elapsed]
aws_db_instance.backend_store: Still creating... [1m10s elapsed]
aws_db_instance.backend_store: Still creating... [1m20s elapsed]
aws_db_instance.backend_store: Still creating... [1m30s elapsed]
aws_db_instance.backend_store: Still creating... [1m40s elapsed]
aws_db_instance.backend_store: Still creating... [1m50s elapsed]
aws_db_instance.backend_store: Still creating... [2m0s elapsed]
aws_db_instance.backend_store: Still creating... [2m10s elapsed]
aws_db_instance.backend_store: Still creating... [2m20s elapsed]
aws_db_instance.backend_store: Still creating... [2m30s elapsed]
aws_db_instance.backend_store: Still creating... [2m40s elapsed]
aws_db_instance.backend_store: Still creating... [2m50s elapsed]
aws_db_instance.backend_store: Still creating... [3m0s elapsed]
aws_db_instance.backend_store: Still creating... [3m10s elapsed]
aws_db_instance.backend_store: Still creating... [3m20s elapsed]
aws_db_instance.backend_store: Still creating... [3m30s elapsed]
aws_db_instance.backend_store: Still creating... [3m40s elapsed]
aws_db_instance.backend_store: Still creating... [3m50s elapsed]
aws_db_instance.backend_store: Still creating... [4m0s elapsed]
aws_db_instance.backend_store: Still creating... [4m10s elapsed]
aws_db_instance.backend_store: Still creating... [4m20s elapsed]
aws_db_instance.backend_store: Still creating... [4m30s elapsed]
aws_db_instance.backend_store: Still creating... [4m40s elapsed]
aws_db_instance.backend_store: Still creating... [4m50s elapsed]
aws_db_instance.backend_store: Still creating... [5m0s elapsed]
aws_db_instance.backend_store: Still creating... [5m10s elapsed]
aws_db_instance.backend_store: Still creating... [5m20s elapsed]
aws_db_instance.backend_store: Still creating... [5m30s elapsed]
aws_db_instance.backend_store: Still creating... [5m40s elapsed]
aws_db_instance.backend_store: Still creating... [5m50s elapsed]
aws_db_instance.backend_store: Still creating... [6m0s elapsed]
aws_db_instance.backend_store: Still creating... [6m10s elapsed]
aws_db_instance.backend_store: Still creating... [6m20s elapsed]
aws_db_instance.backend_store: Still creating... [6m30s elapsed]
aws_db_instance.backend_store: Still creating... [6m40s elapsed]
aws_db_instance.backend_store: Still creating... [6m50s elapsed]
aws_db_instance.backend_store: Still creating... [7m0s elapsed]
aws_db_instance.backend_store: Still creating... [7m10s elapsed]
aws_db_instance.backend_store: Still creating... [7m20s elapsed]
aws_db_instance.backend_store: Still creating... [7m30s elapsed]
aws_db_instance.backend_store: Creation complete after 7m32s [id=mlflow-dev-db]
aws_apprunner_service.server: Creating...
aws_apprunner_service.server: Still creating... [10s elapsed]
aws_apprunner_service.server: Still creating... [20s elapsed]
aws_apprunner_service.server: Still creating... [30s elapsed]
aws_apprunner_service.server: Still creating... [40s elapsed]
aws_apprunner_service.server: Still creating... [50s elapsed]
aws_apprunner_service.server: Still creating... [1m0s elapsed]
aws_apprunner_service.server: Still creating... [1m10s elapsed]
aws_apprunner_service.server: Still creating... [1m20s elapsed]
aws_apprunner_service.server: Still creating... [1m30s elapsed]
aws_apprunner_service.server: Still creating... [1m40s elapsed]
aws_apprunner_service.server: Still creating... [1m50s elapsed]
aws_apprunner_service.server: Still creating... [2m0s elapsed]
aws_apprunner_service.server: Still creating... [2m10s elapsed]
aws_apprunner_service.server: Still creating... [2m20s elapsed]
aws_apprunner_service.server: Still creating... [2m30s elapsed]
aws_apprunner_service.server: Still creating... [2m40s elapsed]
aws_apprunner_service.server: Still creating... [2m50s elapsed]
aws_apprunner_service.server: Still creating... [3m0s elapsed]
aws_apprunner_service.server: Still creating... [3m10s elapsed]
aws_apprunner_service.server: Still creating... [3m20s elapsed]
aws_apprunner_service.server: Still creating... [3m30s elapsed]
aws_apprunner_service.server: Still creating... [3m40s elapsed]
aws_apprunner_service.server: Still creating... [3m50s elapsed]
aws_apprunner_service.server: Still creating... [4m0s elapsed]
aws_apprunner_service.server: Still creating... [4m10s elapsed]
aws_apprunner_service.server: Still creating... [4m20s elapsed]
aws_apprunner_service.server: Still creating... [4m30s elapsed]
aws_apprunner_service.server: Still creating... [4m40s elapsed]
aws_apprunner_service.server: Still creating... [4m50s elapsed]
aws_apprunner_service.server: Still creating... [5m0s elapsed]
aws_apprunner_service.server: Still creating... [5m10s elapsed]
aws_apprunner_service.server: Still creating... [5m20s elapsed]
aws_apprunner_service.server: Still creating... [5m30s elapsed]
aws_apprunner_service.server: Still creating... [5m40s elapsed]
aws_apprunner_service.server: Still creating... [5m50s elapsed]
aws_apprunner_service.server: Still creating... [6m0s elapsed]
aws_apprunner_service.server: Still creating... [6m10s elapsed]
aws_apprunner_service.server: Still creating... [6m20s elapsed]
aws_apprunner_service.server: Creation complete after 6m21s [id,region, ...]

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

Outputs:

artifact_bucket_id = <bucket_name>
mlflow_password = <sensitive>
mlflow_username = <username>
port = 8080
service_url = <url>
status = "RUNNING"

**Comment by SyedHamza0196** [comment]
Update:
url dosen't work with postfix :8080

**Comment by DougTrajano** [comment]
Hi, @SyedHamza0196 sorry for the late answer.

Have you fixed this issue?
