### ISSUE TITLE
Store artifacts to existing bucket

### ISSUE THREAD

**Issue by sofq** [DougTrajano/mlflow-server#173]
Hello @DougTrajano, 

I want to use the existing bucket to store the artifact. But when I run:
```bash
terraform apply -var mlflow_username="admin" -var mlflow_password="12345" -var artifact_bucket_id="mlflow-artifact-feeder"
```
I got below error:  

![image](https://user-images.githubusercontent.com/49865170/185020779-343073c8-f4e1-41e4-b606-52d4a952fb4c.png)  

Would you have any idea of why this happens ? 

Thank you.

**Comment by DougTrajano** [comment]
Hey buddy! It's an issue on the Terraform stack, I'll fix it ASAP.
