### ISSUE TITLE
Getting error in S3 file

### ISSUE THREAD

**Issue by akayalml** [DougTrajano/mlflow-server#200]
I am getting the following error while doing terraform validate. 

`
│ Error: Unsupported argument
│
│   on s3.tf line 3, in module "s3":
│    3:   name                    = local.name
│
│ An argument named "name" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on s3.tf line 4, in module "s3":
│    4:   tags                    = local.tags
│
│ An argument named "tags" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on s3.tf line 5, in module "s3":
│    5:   create_dedicated_bucket = local.create_dedicated_bucket
│
│ An argument named "create_dedicated_bucket" is not expected here.
`

**Comment by DougTrajano** [comment]
Hi @akayalml could you give me more details about how you ran `terraform validate`?

I tried reproducing this error here, but I wasn't able.

Command: `.../mlflow-server\terraform> terraform validate`

```log
Success! The configuration is valid.
```
