### ISSUE TITLE
Multiple user logins

### ISSUE THREAD

**Issue by gohweixun** [DougTrajano/mlflow-server#237]
If I wanted to create multiple user logins for the MLFlow server based on this terraform architecture, how should I do it?

**Comment by DougTrajano** [comment]
It's currently not supported, it's in my backlog but I don't have time to work on it now.

Basically, we need to create a Password File that will be used by NGINX. It's described in [Restricting Access with HTTP Basic Authentication | NGINX Plus](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/).

If you can work on it, I'll be glad to accept your PR.

**Comment by gohweixun** [comment]
Thanks for the explanation. I'm trying to understand how things are setup a little better. After digging a bit into the code, my understanding is that you have built your own custom container image containing both nginx and mlflow, hence any changes to `nginx.sh` would necessitate rebuilding the image, and likewise for updates to mlflow.

I was wondering if there was any way these could be separated, to make use of the [official mlflow image](https://github.com/mlflow/mlflow/pkgs/container/mlflow)?
