### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by anishshah97** [DougTrajano/mlflow-server#28]
The Issue:

Getting a `502: Bad Gateway` error from the deployed app runner app despite following the steps outlined here/in the blog post.
<img width="1017" alt="Screen Shot 2021-09-13 at 1 06 40 PM" src="https://user-images.githubusercontent.com/20888230/133127719-7527e7f3-fdae-4405-925b-5b6573a9a7c5.png">

Steps Taken:

I ran `terraform apply` with no variables and got:
<img width="431" alt="Screen Shot 2021-09-13 at 1 06 32 PM" src="https://user-images.githubusercontent.com/20888230/133127743-095b1b0a-c194-4e04-a504-7c4ccbc8f748.png">

This was able to create all the needed materials for mlflow alongside the proper environment variables named and set
<img width="1564" alt="Screen Shot 2021-09-13 at 1 07 05 PM" src="https://user-images.githubusercontent.com/20888230/133127787-4b6946f8-1ab1-4590-af00-93dca39bd096.png">

<img width="906" alt="Screen Shot 2021-09-13 at 1 06 51 PM" src="https://user-images.githubusercontent.com/20888230/133127811-71d0ece5-c951-4730-be77-902b14e1f861.png">

<img width="1357" alt="Screen Shot 2021-09-13 at 1 08 51 PM" src="https://user-images.githubusercontent.com/20888230/133127857-142a044f-4419-4dfd-98ed-6ed6eb4a6873.png">

The Problem:

The app runner isn't able to connect with RDS despite using the proper credentials set in the environment variables.
<img width="1374" alt="Screen Shot 2021-09-13 at 1 08 40 PM" src="https://user-images.githubusercontent.com/20888230/133127882-ea0f6a76-ab67-493d-aa93-4b26dc415191.png">

**Comment by DougTrajano** [comment]
Hello @anishshah97 

Thanks for letting me know about it.

I'll investigate your issue here and answer you when I have a solution.

**Comment by DougTrajano** [comment]
Hello @anishshah97 I created a new release just to update the Python libs that we use in the project.

So, I deployed the MLflow again using the terraform stack and it works properly. See the logs below.

![image](https://user-images.githubusercontent.com/8703022/133190554-8c2894a3-9d25-4142-95b7-42eee8906595.png)

Could you run `terraform destroy`, delete all terraform temp files, and run again `terraform init && terraform apply`?

**Comment by anishshah97** [comment]
@DougTrajano 
I updated the release, ran the commands provided, and even changed the region to see if that was the issue and it seems my  App Runner still cannot connect to my RDS instance. The error is the same as the already provided images except with the resources in `us-west-2` as opposed to `us-east-1`

**Comment by DougTrajano** [comment]
Hi @anishshah97 sorry for the late answer.

So, probably your default VPC that is assigning to the RDS instance doesn't allow traffic outside the VPC. The AWS App Runner runs in a different VPC.

Check if you are able to connect to your RDS instance from your local machine. Probably not.
