### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by TonyChiangUSA** [DougTrajano/mlflow-server#3]
The Log

`07-27-2021 03:05 PM (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'mlflow-dev-db.xxxxx.us-east-1.rds.amazonaws.com' (timed out)")`

And there's nothing on my s3 console, how to add secrets to s3?

**Comment by DougTrajano** [comment]
Hello @TonyChiangUSA 

Can you check if the RDS Database called `mlflow-dev-db` exists in your AWS Account?

When did you say that "there's nothing on my s3 console" do you mean that you don't have the bucket created or that you want the S3 connection credentials?

This project uses IAM Role to provide access for AWS App Runner connects to your S3 Bucket. So, no credentials are required.

**Comment by TonyChiangUSA** [comment]
> Hello @TonyChiangUSA
> 
> Can you check if the RDS Database called `mlflow-dev-db` exists in your AWS Account?
> 
> When did you say that "there's nothing on my s3 console" do you mean that you don't have the bucket created or that you want the S3 connection credentials?
> 
> This project uses IAM Role to provide access for AWS App Runner connects to your S3 Bucket. So, no credentials are required.

**Comment by DougTrajano** [comment]
Sorry for the late answer. So, I think that your VPC only allows access to internal services and this solution requires that RDS Database be publicly accessible. AWS App Runner doesn't access other resources inside the VPC if they aren't publicly accessible.

**Comment by TonyChiangUSA** [comment]
How to make VPC publicly accessible? There seems no place for configuring VPC on App Runner Console

**Comment by DougTrajano** [comment]
No, actually App Runner creates its own VPC (hidden) to the server. You should check the RDS Database connection. Try to access this DB in your local machine using [MySQL Workbench](https://www.mysql.com/products/workbench/).
